name: Deploy to Remote Server

on:
  workflow_dispatch:  # Для ручного запуска workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create SSH directory and key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_issai
          chmod 600 ~/.ssh/id_issai

      - name: Verify SSH key in agent
        run: |
          ssh-add -l

      - name: Test SSH connection to jump server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_issai -p 11223 rawan_qurmet@87.255.216.119 "echo 'Connected to jump server'"

      - name: Debug SSH connection to remote server via jump server
        run: |
          ssh -vvv -o StrictHostKeyChecking=no -J rawan_qurmet@87.255.216.119 rawan_qurmet@10.6.254.76 "echo 'Connected to remote server'"

      - name: Deploy code
        run: |
          echo "Deploying application..."
