name: SSH via Proxy Jump

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Set up SSH
      run: |
        set -x
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Create SSH config for proxy jump
        echo -e "Host proxy_jump\n  HostName ${{ secrets.PROXY_JUMP_IP }}\n  User rawan_qurmet\n  Port 11223\n  IdentityFile ~/.ssh/id_rsa\n  ForwardAgent yes" > ~/.ssh/config
        echo -e "Host destination_server\n  HostName ${{ secrets.DESTINATION_SERVER_IP }}\n  User rawan_qurmet\n  Port 22\n  ProxyJump proxy_jump\n  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
        
        ssh-keyscan ${{ secrets.PROXY_JUMP_IP }} >> ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets.DESTINATION_SERVER_IP }} >> ~/.ssh/known_hosts
        cat ~/.ssh/config

    - name: Run ls -l command
      run: ssh destination_server 'ls -l /'

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
