name: Test SSH Connection

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_issai
        chmod 600 ~/.ssh/id_issai
        # Add the server IP to the known_hosts file to avoid interactive prompt
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Test SSH Connection
      run: |
        ssh -i ~/.ssh/id_issai rawan_qurmet@${{ secrets.SERVER_IP }} "ls -la"
