name: Deploy to Remote Server

on:
  workflow_dispatch:  # Для ручного запуска workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH connection to jump server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_issai -p 11223 rawan_qurmet@87.255.216.119 "echo 'Connected to jump server'"

      - name: Test SSH connection to remote server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_issai -p 22 rawan_qurmet@10.6.254.76 "echo 'Connected to remote server'"

      - name: Deploy code
        run: |
          # Здесь размещай свои команды для деплоя
          echo "Deploying application..."
