name: Test SSH Connection to Gateway

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-ssh-gateway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Add SSH key
      - name: Add SSH key
        run: |
          echo "${{ secrets.ISSAI_PRIVATE_KEY }}" > id_issai
          chmod 600 id_issai

      # Test SSH connection to gateway
      - name: Test SSH connection to gateway
        run: |
          ssh -i id_issai ${{ secrets.ISSAI_USERNAME }}@${{ secrets.ISSAI_HOST_GATEWAY }} -p 11223 "echo 'SSH connection to gateway successful!'"
