name: Test SSH Connection

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.ISSAI_PRIVATE_KEY }}
        ssh-passphrase: ${{ secrets.ISSAI_PASSPHRASE }}

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ISSAI_PRIVATE_KEY }}" > ~/.ssh/id_issai
        chmod 600 ~/.ssh/id_issai
        echo "${{ secrets.ISSAI_SSH_CONFIG }}" > ~/.ssh/config
        chmod 600 ~/.ssh/config

    - name: Test SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no rawan_qurmet@remote_server -p 22 echo "SSH connection successful"
