name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false
      run: echo "Checked out repository"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      run: echo "Set up Docker Buildx"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      run: echo "Set up QEMU"

    - name: Copy files to Droplet
      run: |
        echo "Copying files to Droplet"
        scp -o StrictHostKeyChecking=no -r ./ root@${{ secrets.DIGITALOCEAN_DROPLET_IP }}:/root/fastapi-app
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DIGITALOCEAN_DROPLET_IP: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}

    - name: Deploy to Droplet
      run: |
        echo "Deploying to Droplet"
        ssh -o StrictHostKeyChecking=no root@${{ secrets.DIGITALOCEAN_DROPLET_IP }} << 'EOF'
          cd /root/fastapi-app
          docker-compose down
          docker-compose up -d --build
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DIGITALOCEAN_DROPLET_IP: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
