name: Test SSH Connection

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Add SSH key
      - name: Add SSH key
        run: |
          echo "${{ secrets.ISSAI_PRIVATE_KEY }}" > id_issai
          chmod 600 id_issai

      # Test SSH connection
      - name: Test SSH connection to remote server
        run: |
          ssh -i id_issai -o ProxyCommand="ssh -W %h:%p -i id_issai -p 11223 ${{ secrets.ISSAI_USERNAME }}@${{ secrets.ISSAI_HOST_GATEWAY }}" ${{ secrets.ISSAI_USERNAME }}@${{ secrets.ISSAI_HOST_REMOTE }} "echo 'SSH connection successful!'"
