name: Deploy FastAPI Project

on:
  workflow_dispatch:  # For manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create SSH directory and key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_issai
          chmod 600 ~/.ssh/id_issai

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 11223 87.255.216.119 >> ~/.ssh/known_hosts
          ssh-keyscan -p 22 10.6.254.76 >> ~/.ssh/known_hosts
        continue-on-error: true

      - name: Deploy FastAPI Project
        run: |
          # Extract the repository name from the GitHub repository context
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          REMOTE_DIR="/srv/issai_projects/$REPO_NAME"

          # Create the project directory on the remote server
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ~/.ssh/id_issai -o "ProxyCommand ssh -i ~/.ssh/id_issai -p 11223 -W %h:%p rawan_qurmet@87.255.216.119" rawan_qurmet@10.6.254.76 << EOF
            mkdir -p $REMOTE_DIR
          EOF

          # Copy the repository content to the remote server
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_issai -r ./ rawan_qurmet@10.6.254.76:$REMOTE_DIR

          # Build and start the containers on the remote server
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ~/.ssh/id_issai -o "ProxyCommand ssh -i ~/.ssh/id_issai -p 11223 -W %h:%p rawan_qurmet@87.255.216.119" rawan_qurmet@10.6.254.76 << EOF
            cd $REMOTE_DIR
            git pull
            docker compose up --build -d
          EOF
