name: Test SSH Connection

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Create .ssh Directory
      run: mkdir -p ~/.ssh

    - name: Add SSH Private Key
      run: |
        echo "${{ secrets.ISSAI_PRIVATE_KEY }}" > ~/.ssh/id_issai
        chmod 600 ~/.ssh/id_issai

    - name: Add Known Hosts
      run: |
        ssh-keyscan -p 11223 -H ${{ secrets.ISSAI_HOST_GATEWAY }} >> ~/.ssh/known_hosts

    - name: Install expect
      run: sudo apt-get install -y expect

    - name: Start SSH Agent and Add Key Using expect
      run: |
        eval $(ssh-agent -s)
        expect << EOF
        spawn ssh-add ~/.ssh/id_issai
        expect "Enter passphrase for ~/.ssh/id_issai:"
        send "${{ secrets.ISSAI_PASSPHRASE }}\r"
        expect eof
        EOF

    - name: Test SSH Connection
      run: |
        ssh -i ~/.ssh/id_issai -o StrictHostKeyChecking=no -o "IdentitiesOnly=yes" -o "NumberOfPasswordPrompts=0" rawan_qurmet@${{ secrets.ISSAI_HOST_GATEWAY }} -p 11223 "ls -la"
