name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Log in to DigitalOcean
      run: echo "Logged in to DigitalOcean"
      
    - name: Copy files to Droplet
      run: |
        echo "Copying files to Droplet"
        scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} -r ./ root@${{ secrets.DIGITALOCEAN_DROPLET_IP }}:/root/fastapi-app

    - name: Deploy to Droplet
      run: |
        echo "Deploying to Droplet"
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} root@${{ secrets.DIGITALOCEAN_DROPLET_IP }} << 'EOF'
          cd /root/fastapi-app
          docker-compose down
          docker-compose up -d --build
        EOF
