name: SSH via Proxy Jump

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Debug Information
      run: |
        echo "ISSAI_GATEWAY_IP: ${{ secrets.ISSAI_GATEWAY_IP }}"
        echo "REMOTE_SERVER_IP: ${{ secrets.REMOTE_SERVER_IP }}"

    - name: Verify Host Connectivity
      run: |
        ping -c 4 ${{ secrets.ISSAI_GATEWAY_IP }} || exit 1
        ping -c 4 ${{ secrets.REMOTE_SERVER_IP }} || exit 1

    - name: Set up SSH
      run: |
        set -x
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Create SSH config for proxy jump
        echo -e "Host issai_gateway\n  HostName ${{ secrets.ISSAI_GATEWAY_IP }}\n  User rawan_qurmet\n  Port 11223\n  IdentityFile ~/.ssh/id_rsa\n  ForwardAgent yes" > ~/.ssh/config
        echo -e "Host remote_server\n  HostName ${{ secrets.REMOTE_SERVER_IP }}\n  User rawan_qurmet\n  Port 22\n  ProxyJump issai_gateway\n  IdentityFile ~/.ssh/id_rsa\n  ForwardAgent yes\n  LocalForward 222 localhost:22" >> ~/.ssh/config
        
        ssh-keyscan -v ${{ secrets.ISSAI_GATEWAY_IP }} >> ~/.ssh/known_hosts || exit 1
        ssh-keyscan -v ${{ secrets.REMOTE_SERVER_IP }} >> ~/.ssh/known_hosts || exit 1
        cat ~/.ssh/config

    - name: Run ls -l command
      run: ssh remote_server 'ls -l /'

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
