name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: ubuntu-latest

    env:
      JUMP_SERVER_USER: ${{ secrets.JUMP_SERVER_USER }}
      JUMP_SERVER_IP: ${{ secrets.JUMP_SERVER_IP }}
      REMOTE_SERVER_USER: ${{ secrets.REMOTE_SERVER_USER }}
      REMOTE_SERVER_IP: ${{ secrets.REMOTE_SERVER_IP }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ env.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ env.JUMP_SERVER_IP }} >> ~/.ssh/known_hosts
        ssh-keyscan -H ${{ env.REMOTE_SERVER_IP }} >> ~/.ssh/known_hosts
        echo "SSH setup completed."

    - name: Verify SSH connection and run command
      run: |
        echo "Testing SSH connection to remote server through jump server"
        ssh -vvv -o StrictHostKeyChecking=no -o ProxyJump=${{ env.JUMP_SERVER_USER }}@${{ env.JUMP_SERVER_IP }} ${{ env.REMOTE_SERVER_USER }}@${{ env.REMOTE_SERVER_IP }} 'echo "Connection successful"; ls -la'
